package com.anfly.collection1908a.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.anfly.collection1908a.ConllectionDbBean;

import com.anfly.collection1908a.dao.ConllectionDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig conllectionDbBeanDaoConfig;

    private final ConllectionDbBeanDao conllectionDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        conllectionDbBeanDaoConfig = daoConfigMap.get(ConllectionDbBeanDao.class).clone();
        conllectionDbBeanDaoConfig.initIdentityScope(type);

        conllectionDbBeanDao = new ConllectionDbBeanDao(conllectionDbBeanDaoConfig, this);

        registerDao(ConllectionDbBean.class, conllectionDbBeanDao);
    }
    
    public void clear() {
        conllectionDbBeanDaoConfig.clearIdentityScope();
    }

    public ConllectionDbBeanDao getConllectionDbBeanDao() {
        return conllectionDbBeanDao;
    }

}
