package com.anfly.exercise11.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.anfly.exercise11.bean.FoodDbBean;

import com.anfly.exercise11.dao.FoodDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodDbBeanDaoConfig;

    private final FoodDbBeanDao foodDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodDbBeanDaoConfig = daoConfigMap.get(FoodDbBeanDao.class).clone();
        foodDbBeanDaoConfig.initIdentityScope(type);

        foodDbBeanDao = new FoodDbBeanDao(foodDbBeanDaoConfig, this);

        registerDao(FoodDbBean.class, foodDbBeanDao);
    }
    
    public void clear() {
        foodDbBeanDaoConfig.clearIdentityScope();
    }

    public FoodDbBeanDao getFoodDbBeanDao() {
        return foodDbBeanDao;
    }

}
